%include offset or not and should i truncate data?
loren_fun1d = @(b,x) b(1)./((x-b(3)).^2+b(2).^2)+b(4);
coeff_names={'amp','sig','mu','offset'};

fo = statset('TolFun',10^-6,...
    'TolX',1e-4,...
    'MaxIter',1e4,...
    'UseParallel',1);
inital_guess=[4e-6,4,2.99,0];
fitobject_l=fitnlm(f,dT_dt./P,...
    loren_fun1d,...
    inital_guess,...
    'CoefficientNames',coeff_names,'Options',fo)
fit_coeff_l=fitobject_l.Coefficients.Estimate;
fit_unc_l=fitobject_l.Coefficients.SE;
int_1 = (v0+fit_coeff_l(3)*1e6).*pi*fit_coeff_l(1)/abs(fit_coeff_l(2))*1e6;

int_1_err = int_1*sqrt((fit_unc_l(1)/fit_coeff_l(1)).^2+(fit_unc_l(2)/fit_coeff_l(2)).^2)