loren_fun1d = @(b,x) b(1)./((x-b(3)).^2+b(2).^2);
coeff_names={'amp','mu','sig'};

fo = statset('TolFun',10^-6,...
    'TolX',1e-4,...
    'MaxIter',1e4,...
    'UseParallel',1);
inital_guess=[4e-3,10,4];
fitobject_l=fitnlm(f,dT_dt,...
    loren_fun1d,...
    inital_guess,...
    'CoefficientNames',coeff_names,'Options',fo)
fit_coeff_l=fitobject_l.Coefficients.Estimate;
int_1 = (predicted_freq+fit_coeff_l(3))*1e6.*pi*fit_coeff_l(1)/fit_coeff_l(2);